### ISSUE TITLE
ruby-head, trunk, master

### ISSUE THREAD

**Issue by MSP-Greg** [actions/setup-ruby#14]
Has thought been given to having a 'Ruby-head' version available for CI?

**Comment by damccorm** [comment]
`ruby-head` is just the latest release, right? I think in theory this would be a good idea, but I have hesitations about our ability to keep up with images. We don't generate a new image every time a new version of ruby is released, and since we don't have a way of downloading versions/have to rely on our cache, it seems like we would often get out of sync with the actual `ruby-head`.

**Comment by MSP-Greg** [comment]
Travis has a daily build, I've never really checked, but I assume it's somewhere on their network.  It can be added to the job matrix, and that's all it takes.

AppVeyor doesn't, but builds are available from an AppVeyor repo.  It takes a few lines of script to download and install with 7zip.

**Comment by damccorm** [comment]
So I think you've kinda hit on the issue there - we want to maintain parity between platforms, and we're also not currently in a place where we're ready to create/maintain our own ruby distro. With that said, that's something I'd be potentially interested in going forward, so I definitely want to leave this open.

**Comment by eregon** [comment]
To clarify, `ruby-head` refers to building MRI from the latest `master` commit, not the last stable release.

**Comment by andymeneely** [comment]
As a gem maintainer, being able to test my code against `ruby-head` is a key reason I use CI. It lets me see new features long before my users do without having to wade through Ruby's changelogs regularly.

For example, today on Travis I realized that my code would throw warnings on the to-be-released Ruby 2.7 because of them changing the way they handle keyword arguments. Now I have months to fix the problem instead of days.

For now I'll attempt to build Ruby in the action itself, but it would be ideal if `ruby-head` builds were cached the way Travis does.

**Comment by MSP-Greg** [comment]
@damccorm 

>  but I have hesitations about our ability to keep up with images. We don't generate a new image every time a new version of ruby is released

How often does MSFT/GH expect to update images?  New Ruby versions aren't released that often...

@andymeneely 

have a look at https://github.com/rubygems/rubygems/blob/master/.github/workflows/ubuntu-rvm.yml, which uses rvm with the current Travis build.

I plan on creating a ruby-head for Windows as a GH release, I may try to do the same with at least one Ubuntu build.  They would be relatively easy to install in Actions.  Not at the top of my OSS list.

**Comment by MSP-Greg** [comment]
@eileencodes

Glad to see you're involved.

I'll close this, as issue https://github.com/actions/setup-ruby/issues/44 has some discussion of this.

I think the immediate goal is to get better version support with current releases, and support ruby-master later.  Obviously, right now it's not that much different that 2.7.0...
