### ISSUE TITLE
Readline support

### ISSUE THREAD

**Issue by ibrasho** [actions/setup-ruby#17]
I was trying to use `actions/setup-ruby` in a Rails project and was surprised to see that ruby was installed with no readline support. If you use `byebug` or any other similar tools, you won't be able to run any commands from your project.

> Sorry, you can't use byebug without Readline. To solve this, you need to
>    rebuild Ruby with Readline support. If using Ubuntu, try `sudo apt-get
>    install libreadline-dev` and then reinstall your Ruby.

Is there a way to get a ruby version that's compiled with readline support? Or are we forced to use Docker images?

**Comment by damccorm** [comment]
@kaylangan who I believe was working on readline support.

**Comment by kaylangan** [comment]
This will be rolling out in this week's deployment. I'll update this issue when it's available.

**Comment by obahareth** [comment]
❤️ ❤️ for the epic fast responses and action!

**Comment by MSP-Greg** [comment]
@kaylangan, @ibrasho

> Is there a way to get a ruby version that's compiled with readline support?

Ruby versions 2.4 and later ship with MSYS2 readline dll's.  I believe the real issue is being able to install/build extension gems like byebug.

To do so requires the MSYS2 build tools to be available, along with the MSYS readline package.  Different packages may be required for other extension gems.

For those that may not be aware, MSYS is a system of packages and build tools, allowing code to be compiled using gcc based compilers.  Publicly available Ruby versions and most Windows pre-compiled gems are compiled with this system.  Most extension gems are also CI tested using MSYS2.

I asked about this issue in Issue #13...

**Comment by ibrasho** [comment]
I'm mainly using Linux (specifically Ubuntu) runners, so I'm not sure MSY2 is cause for the issue I'm talking about. :rose:

**Comment by MSP-Greg** [comment]
You're correct, a stupid moment on my part.  I guess I assumed that all the std-lib's would function, and I thought that unlikely to break on Ubuntu.

Also, byebug requires Ruby readline as a runtime dependency, it doesn't need the readline library files to compile.

So I was mistaken on two counts.  Sorry, was out the door (rushed) when I wrote the above...

**Comment by ibrasho** [comment]
It working for me now. Thanks!
